version: '3.9'

services:
  frontend:
    build: ../frontend_react/.
    volumes:
      - frontend:/app/build
    depends_on:
      - db

  api:
    build: . # /code
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/usr/src/app/
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: skyuser
      POSTGRES_PASSWORD: skypassword
      POSTGRES_DB: skytodolist
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  frontend: