name: Build and deploy action
on:
  push:
    branches: ["main"]

jobs:
  build_and_push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true

      - name: Build and Push Container
        run: |-
          docker build -t sergdef/todolist_skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
          docker push sergdef/todolist_skypro:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: '${{ secrets.SQL_DB_NAME }}'
      POSTGRES_USER: '${{ secrets.SQL_DB_USER }}'
      POSTGRES_PASSWORD: '${{ secrets.SQL_DB_PASSWORD }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: render config
        run: |-
          mkdir deploy
          echo docker-compose-ci.yml | envsubst > deploy/docker-compose.yaml

#      - name: Clone files to server
##        uses: siva1024/scp-deployer@latest
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
##          port: ${{ secrets.PORT }}
#          source: "deploy/docker-compose.yaml"
#          target: "/home/skypro/deploy/"
#          strip_components: 1

      # ===== BEGIN SSH EXIT =========
      - name: clone files to server
        uses: appleboy/scp-action@master
        with:
          # Эти значения надо вписать в секреты гитхаба
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: '${{ secrets.SSH_USERNAME }}'
#          password: '${{ secrets.SSH_PASSWORD }}'
          key: '${{ secrets.SSH_PRIVATE_KEY }}'
          # Указываем, какие файлы копировать
          source: "deploy/docker-compose.yaml"
          target: "/home/skypro/deploy/"
          strip_components: 1
      - name: Print Info
        run: echo "Deploy at https://${BRANCH_NAME}.app.example.ru/"

#      - name: Executing remote SSH commands using SSH_KEY
#        uses: appleboy/ssh-action@v0.1.8
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          script: |-
#            whoami
#            cd todolist
#            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d
        
